server:  
  port: ${PORT:4444}

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 2000
  


logging:
  level:
    com.netflix.ribbon: DEBUG
    com.netflix.hystrix: DEBUG

#Enable for Scenarios 1,2,3
feign:
  hystrix:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
                      
spring:
  sleuth:
    hystrix:
      strategy:
        enabled: true                      